# Generated by Django 3.2.9 on 2022-02-21 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HostelApp', '0005_auto_20220220_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='room',
        ),
    ]
