# Generated by Django 3.2.9 on 2022-02-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostelApp', '0009_profile_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
