# Generated by Django 3.2.9 on 2022-02-24 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HostelApp', '0010_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='in_charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HostelApp.matron'),
        ),
    ]
