# Generated by Django 3.2.9 on 2022-02-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostelApp', '0012_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.CharField(choices=[('1', '401'), ('2', '402'), ('3', '403'), ('4', '404'), ('5', '405'), ('6', '406'), ('7', '407'), ('8', '408'), ('9', '409'), ('10', '410')], max_length=5),
        ),
    ]
