# Generated by Django 3.2.9 on 2022-02-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostelApp', '0015_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.BooleanField(choices=[('Booked', 'Booked'), ('Available', 'Available')], null=True),
        ),
    ]
