# Generated by Django 3.2.9 on 2022-02-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostelApp', '0017_auto_20220228_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Available', 'Available')], max_length=20, null=True),
        ),
    ]
