# Generated by Django 3.2.9 on 2022-02-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostelApp', '0018_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(blank=True, choices=[('Booked', 'Booked'), ('Available', 'Available')], max_length=20, null=True),
        ),
    ]
