# Generated by Django 3.2.9 on 2022-03-03 09:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HostelApp', '0019_alter_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='room_image'),
        ),
    ]
