# Generated by Django 3.2.9 on 2022-03-06 06:52

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HostelApp', '0021_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='post_image')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HostelApp.student')),
            ],
        ),
    ]
