# Generated by Django 3.2.9 on 2022-03-06 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HostelApp', '0023_auto_20220306_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='occupant',
        ),
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_owner', to='HostelApp.room'),
        ),
    ]
